// <auto-generated />
using MVCSlideshowViewComponent.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCSlideshowViewComponent.Data.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20230814191018_Ilk")]
    partial class Ilk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCSlideshowViewComponent.Data.BilgeSoz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Soz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yazar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BilgeSozler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Soz = "Yılanı kendi ellerinle öldür",
                            Yazar = "Yiğit HACIEFENDİOĞLU"
                        },
                        new
                        {
                            Id = 2,
                            Soz = "May the source be with you",
                            Yazar = "Sinan \" Yoda \" TAŞYAPAR"
                        },
                        new
                        {
                            Id = 3,
                            Soz = "Habibi come to Dubai",
                            Yazar = "Batuhan HAYBEK"
                        },
                        new
                        {
                            Id = 4,
                            Soz = "Ne olursan ol yine de gel",
                            Yazar = "Ozan GENÇ"
                        },
                        new
                        {
                            Id = 5,
                            Soz = "Sinan anladın mı, Ozan anladın mı, Batuhan anladın mı, Emrah anladın mı, Dogukan, Serdar, Taylan, Yasin, Ceren, Gamze, Kiziltan herkes anladıysa devam edelim",
                            Yazar = "Alp CEYHAN"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
